### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "laurent.leleux@vinci.be",
  "password": "Prof24,z"
}

> {%
  client.global.set("token", response.body.token);
%}

### Get number of user with & without stages
GET {{baseUrl}}/contact/users-stages
Content-Type: application/json
Authorization: {{token}}


### Get company with thei number of stage
GET {{baseUrl}}/company
Content-Type: application/json
Authorization: {{token}}
